CC=gcc -std=gnu11
base=src/routine_base.c src/stack_collect.c src/util/reuse.c src/routine_helper.c src/routine_user_api.c src/routine_dfa.c src/routine_common.c src/routine_event.c

linux: $(base) src/routine_freebsd.s main_t.c
	$(CC) $^ -o $@ 

check:
	make checker

distcheck:
	make bitmap

lib:
	mkdir build
	gcc -c src


include ./test/makefile
.PHONY:clean
clean:
	rm *.o freebsd linux

